# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-20 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteDash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='created_by',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_address',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
